### ISSUE TITLE
Integration in a modpack

### ISSUE THREAD

**Issue by andrejfox** [georgebjork/LC-MoreMusicMod#1]
Is there a way i can make a modpack and include some songs in it? i have tried doing something like this but it didn't work: modpackRoot\plugins\MoreMusic\Music\.mp3

**Comment by georgebjork** [comment]
Hi @ANDREJ6693 

I believe this should be possible in its current implementation. However, I have not played around with mod packs much, so I have not tested this, and could be wrong. I can check tomorrow. 

I would first check to make sure the MoreMusic.dll exists in the plugins folder. Then, I would make sure the music is in the correct folder. It should be "MoreMusic/Music/{music_goes_in_here}". When launching the game with the mod, you should see a debug output of it loading the songs. If no songs exist, then it should say "No songs where found at {directory_here}"

Let me know if this resolves your issue. If not, feel free to send your mod pack my way so I can try and reproduce 😎

**Comment by andrejfox** [comment]
oki, ill try in a bit. tnx for the response😋

**Comment by andrejfox** [comment]
i have created a modpack for testing this https://thunderstore.io/c/lethal-company/p/Amanda/Modpack_testing_MoreMusicMod/
and the mod itself loads good, but the songs, witch in the modpack are stored in "MusicModpack\BepInEx\plugins\MoreMusic\Music\{someting.mp4}" don't get put in the "{tunderstore profile}\BepInEx\plugins\MoreMusic\Music" but stay in "{tunderstore profile}\BepInEx\plugins\Amanda-Modpack_testing_MoreMusicMod\MoreMusic\Music". also this part from the plugin gets cut out when the modpack is downloaded "...\BepInEx\plugins\...". I think the problem is in the way i am trying to put the MoreMusic folder in the plugins folder, instead of beeing placed in plugins it stays in the modpack folder. do you know any way to properly put MoreMusic\Music  in the BepInEx\plugins folder threw a modpack?

here is the git: https://github.com/ANDREJ6693/LethalCompany_Modpacks

**Comment by georgebjork** [comment]
Hmmm, hopefully I am understanding your issue correctly. If not, please let me know.

When I downloaded your test modpack from thunderstore, I saw this directory "BepInEx/plugins/MoreMusic/Music/{two_songs_here}". This does seem to be the correct file structure. When I added this all to my game, the mod failed to launch and only default music played from the boombox. When investigating, I noticed that the MoreMusic.dll was missing from the plugins which would prevent the mod from loading properly. When I added the .dll it worked fine. 

Ive attached an image to what my file structure looks like. This is in "BepInEx/plugins"

![Screenshot 2023-12-29 014947](https://github.com/georgebjork/LC-MoreMusicMod/assets/34782305/8a4d8fbb-a907-4999-864b-1d63b564d9cd)


Can you please try and bundle the MoreMusic.dll with the modpack and see if that has better results?

**Comment by andrejfox** [comment]
oki, i will. but are you ok with me having your .dll just like that. i have heard this can be recognised as theft if i dont own the dll

**Comment by georgebjork** [comment]
Absolutely 🙂 

My code is licensed with an MIT license. (https://mit-license.org/). In short you can do almost whatever you want with it. That link will explain it all. 

The .dll is the complied code and is needed for BepInEx to inject it into the game when needed. 

Let me know if you have better results. 

Also, be on the look out for a minor updated release of the mod today. It should hopefully improve the multiplayer experience by the playing the same song for everyone. I believe this would be helpful for your mod pack. All you'll need to do is download the replace the .dll in your mod pack with the updated .dll available on GitHub or Thunderstore and make a new release of your modpack 🙂

**Comment by andrejfox** [comment]
great, ill keep an eye on it. in a bit ill also test how it works if i put the dll in the plugins folder.

**Comment by georgebjork** [comment]
New version is out 😎

**Comment by andrejfox** [comment]
:sunglasses:

**Comment by andrejfox** [comment]
hmm i am still having some problems. I am installing the modpack threw tunderstore and when i do so it doesen't put the "MoreMusic/Music/{.mp4}" in "plugins/" but in "plugins/Amanda-Modpack_testing_MoreMusicMod". so the mod loads fine and generates a empty "plugins/MoreMusic/Music". Is there any way it wuld automaticaly mode the "MoreMusic/Music/{.mp4}" once somone downloads the modpack from the tunderstore app.

![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/a040a298-385a-4bc7-aabe-6a54a431d6ba)
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/745a3138-7774-4304-84da-bd058a9e18cc)
it looks like the mod loads fine and creates the empty "plugins/MoreMusic/Music"
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/34e6987f-92b1-434b-b9fa-493f69e7d4e7)

here is the structure of the modpack
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/f7975f2a-a04f-47d4-8d89-bc3bf30aec78)
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/935e27e9-1713-4c1f-a0e4-184f1a082a80)
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/1f42350a-7aaf-4397-afc5-467afd100a65)

**Comment by georgebjork** [comment]
Ok I think I see the issue. Let me play around with this so this works more friendly with Mod Managers for mod packs

**Comment by georgebjork** [comment]
Ok, I think I have an idea for a solution. I am working on the code for it now.

**Comment by georgebjork** [comment]
I have just pushed a new release. Of the mod. Now reference 1.0.2 in your manifest.json

The mod will now look into each folder in the plugins directory. If it finds `MoreMusic\Music` in a folder like it is in your `Amanda-Modpack_testing_MoreMusicMod\MoreMusic\Music` then it will copy the files into a shared folder it creates. Just make sure to delete the `MoreMusic\Music` folder before you launch the game for the very first time. It will create a new folder and and do its process of finding and moving files. 

I hope this is the solution works 🙂 Sorry for not understanding the first time! I didnt releaize you where using a mod manager and I have a much better understanding of how the mod managers work now and how mod packs work with it!

**Comment by andrejfox** [comment]
Yo tnx soo much. Ill test it out in a bit, but i am sure this will work.

**Comment by andrejfox** [comment]
yep it works
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/3f6cb67a-948b-4ad8-ac93-07e3d9717c9d)
![image](https://github.com/georgebjork/LC-MoreMusicMod/assets/108818069/83822780-662a-4229-8d74-5a1df541f05f)

**Comment by andrejfox** [comment]
tnx a bunch, great work

**Comment by georgebjork** [comment]
Glad to see it's working! Have fun with the mod!!

**Comment by ANDREJ6693** [comment]
tnx, bey

**Comment by andrejfox** [comment]
tnx, bye
